repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: sensitive-info-check
        name: Sensitive Info / Secrets / Paths Check
        entry: bash hooks/sensitive_check.sh
        language: system
        pass_filenames: true
        files: \.(py|R|ipynb)$
