repos:
  # --- 1. Built-in sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # --- 2. Custom lightweight security scanner
  - repo: local
    hooks:
      - id: sensitive-info-check
        name: Sensitive Info / Secrets / Paths Check
        entry: ".\\hooks\\run_sensitive_check.bat"
        language: system
        pass_filenames: true
        files: \.(py|R|ipynb)$
