name: Secure Code Scan (Gitleaks)

on:
  push:
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --no-git -v --redact --exit-code 1 --config .gitleaks.toml

      - name: Custom regex fallback (optional)
        run: |
          echo "🔍 Running custom pattern checks..."
          FOUND=$(grep -rEni \
            -e '(/Users/|C:\\\\Users\\\\)' \
            -e 'password\s*=' \
            -e 'db_password\s*=' \
            -e 'api[_-]?key\s*=' \
            . --include="*.py" --include="*.R" --include="*.ipynb" || true)
          if [ ! -z "$FOUND" ]; then
            echo "❌ Found suspicious patterns:"
            echo "$FOUND"
            exit 1
          else
            echo "✅ No custom issues found."
          fi
